# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fastrls_wrappers", use_symbols = TRUE, package_name = "fastrls")

#' @usage NULL
#' @useDynLib fastrls, .registration = TRUE
NULL

walkdir <- function(dir, include_dirs) .Call(wrap__walkdir, dir, include_dirs)

walkdirp <- function(dir, include_dirs) .Call(wrap__walkdirp, dir, include_dirs)


# nolint end
